stat_list = {
    "opponent": "opp",
    "outcome": "game_outcome",
    "record": "team_record",
    "location": "game_location",
    "points": "pts_off",
    "rush yards": "rush_yds_off",
    "pass yards": "pass_yds_off",
    "total yards": "to_off",
    "first downs defended": "first_down_def",
    "yards defended": "yards_def",
    "pass yards defended": "pass_yds_def",
    "rush yards defended": "rush_yds_def",
    "expected points": "exp_pts_off",
    "expected defensive points": "exp_pts_def",
    "expected special teams points": "exp_pts_st",
}